#pragma once

#include <QAction>
#include <QApplication>
#include <QCheckBox>
#include <QComboBox>
#include <QCursor>
#include <QDebug>
#include <QDialog>
#include <QFont>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QIcon>
#include <QLabel>
#include <QLineEdit>
#include <QMessageBox>
#include <QMouseEvent>
#include <QPainter>
#include <QPixmap>
#include <QPushButton>
#include <QSettings>
#include <QSound>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QTimer>
#include <QVBoxLayout>
#include <QWidget>
#include <Qt>

#include "stdc++.h"